### ISSUE TITLE
find_and_modify

### ISSUE THREAD

**Issue by mrjoes** [ajdavis/mongo-python-driver#3]
Hi,

At appears that `find_and_modify` does not return cursor, while `find` does.

I tried to do use `find` implementation for `find_and_modify`, but it crashes with some weird exception:

```
ERROR:root:Exception in callback <tornado.stack_context._StackContextWrapper object at 0x10f791998>
Traceback (most recent call last):
  File "/Users/serge/Work/venv/lib/python2.7/site-packages/tornado/ioloop.py", line 421, in _run_callback
    callback()
  File "/Users/serge/Work/venv/lib/python2.7/site-packages/tornado/gen.py", line 120, in wrapper
    runner.run()
  File "/Users/serge/Work/venv/lib/python2.7/site-packages/tornado/gen.py", line 345, in run
    yielded = self.gen.send(next)
  File "/Users/serge/Work/venv/prj/actionserv/actionserv/actions/publish.py", line 36, in _handle
    messages = yield motor.Op(pq.find_and_modify(remove=True).to_list)
  File "/Users/serge/Work/socialabs/os/mongo-python-driver/motor/__init__.py", line 1070, in find_and_modify
    cursor = self.delegate.find_and_modify(*args, **kwargs)
  File "/Users/serge/Work/socialabs/os/mongo-python-driver/pymongo/collection.py", line 1272, in find_and_modify
    **kwargs)
  File "/Users/serge/Work/socialabs/os/mongo-python-driver/pymongo/database.py", line 388, in command
    result = self["$cmd"].find_one(command, **extra_opts)
  File "/Users/serge/Work/socialabs/os/mongo-python-driver/pymongo/collection.py", line 516, in find_one
    for result in self.find(spec_or_id, *args, **kwargs).limit(-1):
  File "/Users/serge/Work/socialabs/os/mongo-python-driver/pymongo/cursor.py", line 778, in next
    if len(self.__data) or self._refresh():
  File "/Users/serge/Work/socialabs/os/mongo-python-driver/pymongo/cursor.py", line 729, in _refresh
    self.__uuid_subtype))
  File "/Users/serge/Work/socialabs/os/mongo-python-driver/pymongo/cursor.py", line 666, in __send_message
    **kwargs)
  File "/Users/serge/Work/socialabs/os/mongo-python-driver/pymongo/connection.py", line 905, in _send_message_with_response
    sock_info = self.__socket()
  File "/Users/serge/Work/socialabs/os/mongo-python-driver/pymongo/connection.py", line 689, in __socket
    sock_info = self.__pool.get_socket((host, port))
  File "/Users/serge/Work/socialabs/os/mongo-python-driver/pymongo/pool.py", line 247, in get_socket
    sock_info, from_pool = self.connect(pair), False
  File "/Users/serge/Work/socialabs/os/mongo-python-driver/motor/__init__.py", line 293, in connect
    motor_sock = self.create_connection(pair)
  File "/Users/serge/Work/socialabs/os/mongo-python-driver/motor/__init__.py", line 249, in create_connection
    assert greenlet.getcurrent().parent, "Should be on child greenlet"
AssertionError: Should be on child greenlet
```

How do I make it return cursor?

**Comment by eguven** [comment]
`find_and_modify` returns a single object or `None`, not a cursor (in compliance with pymongo).

**Comment by mrjoes** [comment]
Ah, thank you, missed that part. When I read the Mongo document, I saw query spec, so decided it is same as `find`, but with atomic update/remote operation over matched entities.

**Comment by eguven** [comment]
`MotorCollection.update` is I think what you are looking for. With `multi=True` kwarg, it modifies all matched documents. [doc](http://emptysquare.net/motor/pymongo/api/motor/motor_collection.html#motor.MotorCollection.update)

**Comment by ajdavis** [comment]
Serge, @eguven is right about `find_and_modify` versus `find` versus `update`. But that exception you pasted **is** bizarre, could you provide some example code that causes it? I'd like to make the exception clearer if someone else makes the same mistake.

**Comment by mrjoes** [comment]
I stumbled upon piece of code in a project, where guys were using Mongo as simple queue. However, they were using `find` with `remove`, which worked fine until new worker was added.

So, I thought it should be easier to use `find_and_modify` to get items from queue and remove them from queue as one operation, so there won't be any race condition between two servers. `find_and_modify` returning one item should work, but will require multiple calls to the server to get all data from the queue.

Anyway, it's very easy to reproduce this exception, put this as implementation of the `find_and_modify` in your Collection wrapper class:

```
def find_and_modify(self, *args, **kwargs):
        """Create a :class:`MotorCursor`. Same parameters as for
        :meth:`~pymongo.collection.Collection.find_and_modify`.

        Note that :meth:`find` does not take a `callback` parameter -- pass
        a callback to the :class:`MotorCursor`'s methods such as
        :meth:`MotorCursor.find_and_modify`.

        # TODO: examples of to_list and next
        """
        if 'callback' in kwargs:
            raise pymongo.errors.InvalidOperation(
                "Pass a callback to next_object, each, to_list, count, or tail,"
                "not to find"
            )

        cursor = self.delegate.find_and_modify(*args, **kwargs)
        return MotorCursor(cursor, self)
```

**Comment by ajdavis** [comment]
Oh, ok, that makes sense. You can't do any I/O on a delegate (in this case,
a collection) from the main greenlet. You're not intended to use the
delegate directly, only through Motor's published methods.

When Motor does IO, it spawns a child greenlet and does IO from there. You
need asynchronize(). But in any case, find_and_modify is already
implemented correctly in Motor so you can just use that. =)

http://emptysquare.net/motor/pymongo/api/motor/motor_collection.html#motor.MotorCollection.find_and_modify
