### ISSUE TITLE
/pymongo-2.2.1 fails tests with cpython-3.2

### ISSUE THREAD

**Issue by idella** [ajdavis/mongo-python-driver#4]
# python -V   Python 3.2.3

pymongo  versions  2.2.1  & 2.3

result.
- Testing of dev-python/pymongo-2.3 with CPython 3.2...
  forked process: 26813
  all output going to: /mnt/gen2/TmpDir/portage/dev-python/pymongo-2.3/temp/tests-3.2/mongo.log
  child process started successfully, parent exiting
  PYTHONPATH=build-3.2/lib.linux-x86_64-3.2 nosetests --verbosity=1
  EEE
  ======================================================================
  ERROR: Failure: NameError (global name 'basestring' is not defined)
  ----------------------------------------------------------------------
  Traceback (most recent call last):
  File "/usr/lib64/python3.2/site-packages/nose/failure.py", line 37, in runTest
    raise self.exc_class(self.exc_val).with_traceback(self.tb)
  File "/usr/lib64/python3.2/site-packages/nose/loader.py", line 390, in loadTestsFromName
    addr.filename, addr.module)
  File "/usr/lib64/python3.2/site-packages/nose/importer.py", line 39, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/usr/lib64/python3.2/site-packages/nose/importer.py", line 86, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/mnt/gen2/TmpDir/portage/dev-python/pymongo-2.3/work/pymongo-2.3/gridfs/**init**.py", line 23, in <module>
    from gridfs.errors import (NoFile,
  File "/mnt/gen2/TmpDir/portage/dev-python/pymongo-2.3/work/pymongo-2.3/gridfs/errors.py", line 17, in <module>
    from pymongo.errors import PyMongoError
  File "/mnt/gen2/TmpDir/portage/dev-python/pymongo-2.3/work/pymongo-2.3/pymongo/**init**.py", line 58, in <module>
    version = get_version_string()
  File "/mnt/gen2/TmpDir/portage/dev-python/pymongo-2.3/work/pymongo-2.3/pymongo/**init**.py", line 54, in get_version_string
    if isinstance(version_tuple[-1], basestring):
  NameError: global name 'basestring' is not defined
  ======================================================================
  ERROR: Failure: NameError (global name 'basestring' is not defined)
  ----------------------------------------------------------------------
  Traceback (most recent call last):
  File "/usr/lib64/python3.2/site-packages/nose/failure.py", line 37, in runTest
    raise self.exc_class(self.exc_val).with_traceback(self.tb)
  File "/usr/lib64/python3.2/site-packages/nose/loader.py", line 390, in loadTestsFromName
    addr.filename, addr.module)
  File "/usr/lib64/python3.2/site-packages/nose/importer.py", line 39, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/usr/lib64/python3.2/site-packages/nose/importer.py", line 86, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/mnt/gen2/TmpDir/portage/dev-python/pymongo-2.3/work/pymongo-2.3/pymongo/**init**.py", line 58, in <module>
    version = get_version_string()
  File "/mnt/gen2/TmpDir/portage/dev-python/pymongo-2.3/work/pymongo-2.3/pymongo/**init**.py", line 54, in get_version_string
    if isinstance(version_tuple[-1], basestring):
  NameError: global name 'basestring' is not defined
# 
## ERROR: Failure: SyntaxError (invalid syntax (test_connection.py, line 121))

Traceback (most recent call last):
  File "/usr/lib64/python3.2/site-packages/nose/failure.py", line 37, in runTest
    raise self.exc_class(self.exc_val).with_traceback(self.tb)
  File "/usr/lib64/python3.2/site-packages/nose/loader.py", line 390, in loadTestsFromName
    addr.filename, addr.module)
  File "/usr/lib64/python3.2/site-packages/nose/importer.py", line 39, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/usr/lib64/python3.2/site-packages/nose/importer.py", line 86, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/mnt/gen2/TmpDir/portage/dev-python/pymongo-2.3/work/pymongo-2.3/test/**init**.py", line 18, in <module>
    from test.test_connection import get_connection
  File "<string>", line None
SyntaxError: invalid syntax (test_connection.py, line 121)

---

Ran 3 tests in 0.076s

FAILED (errors=3)
- ERROR: dev-python/pymongo-2.3 failed (test phase):

**Comment by ajdavis** [comment]
Hey, are you trying to install Motor or just PyMongo? If PyMongo, you should report this bug on PyMongo's main repo:

https://github.com/mongodb/mongo-python-driver

In any case, PyMongo 2.2.1 and 2.3 both support all versions of Python 3. Are you running the tests like this?:

python3.2 setup.py test

**Comment by idella** [comment]
In a word, no. Not in gentoo

**Comment by behackett** [comment]
This shows the problem:

File "/mnt/gen2/TmpDir/portage/dev-python/pymongo-2.3/work/pymongo-2.3/pymongo/**init**.py", line 54, in get_version_string...

Gentoo's distutils_src_test command isn't playing nicely with running pymongo's tests under python 3. It's basically trying to run the tests against the 2.x source instead of the 2to3 converted code in build/lib-linux-x86_64-3.2

This is an issue with gentoo's ebuild, not pymongo.

**Comment by ajdavis** [comment]
Thanks @behackett . @idella , I suggest you take this up with the package maintainer for PyMongo on Gentoo, which isn't 10gen. Sorry. PyMongo itself, and its tests, are fully Python 3 compatible, but the Gentoo package isn't running the tests correctly for Python 3.
