### ISSUE TITLE
'ObjectId' object is not iterable

### ISSUE THREAD

**Issue by ghost** [ajdavis/mongo-python-driver#5]
hi, i want to package the function which deal with mongodb, and call the function with motor.Op。for example: 

@gen.engine
def func( callback ):
    ......

in the handler, call it with motor.Op:

@gen.engine
def get( self ):
    result = yield motor.Op( func )

but i got error: 
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/tornado-2.4.post1-py2.7.egg/tornado/web.py", line 1043, in _stack_context_handle_exception
    raise_exc_info((type, value, traceback))
  File "/Library/Python/2.7/site-packages/tornado-2.4.post1-py2.7.egg/tornado/stack_context.py", line 237, in _nested
    yield vars
  File "/Library/Python/2.7/site-packages/tornado-2.4.post1-py2.7.egg/tornado/stack_context.py", line 210, in wrapped
    callback(_args, *_kwargs)
  File "/Library/Python/2.7/site-packages/tornado-2.4.post1-py2.7.egg/tornado/gen.py", line 405, in inner
    self.set_result(key, result)
  File "/Library/Python/2.7/site-packages/tornado-2.4.post1-py2.7.egg/tornado/gen.py", line 335, in set_result
    self.run()
  File "/Library/Python/2.7/site-packages/tornado-2.4.post1-py2.7.egg/tornado/gen.py", line 365, in run
    yielded = self.gen.send(next)
  File "/Users/shiyanhui/Documents/workspace/Roseyears/asytormongo/document.py", line 73, in insert
    callback( result )
  File "/Library/Python/2.7/site-packages/tornado-2.4.post1-py2.7.egg/tornado/gen.py", line 405, in inner
    self.set_result(key, result)
  File "/Library/Python/2.7/site-packages/tornado-2.4.post1-py2.7.egg/tornado/gen.py", line 335, in set_result
    self.run()
  File "/Library/Python/2.7/site-packages/tornado-2.4.post1-py2.7.egg/tornado/gen.py", line 363, in run
    yielded = self.gen.throw(*exc_info)
  File "/Users/shiyanhui/Documents/workspace/Roseyears/app/community/handler.py", line 106, in get
    result = yield motor.Op( node_document.insert, document )
  File "/Library/Python/2.7/site-packages/tornado-2.4.post1-py2.7.egg/tornado/gen.py", line 355, in run
    next = self.yield_point.get_result()
  File "/Library/Python/2.7/site-packages/motor/__init__.py", line 1756, in get_result
    (result, error), _ = super(Op, self).get_result()
TypeError: 'ObjectId' object is not iterable

but with gen.Task it's ok:

@gen.engine
def get( self ):
    result = yield gen.Task( func )

can you help me?

**Comment by ajdavis** [comment]
Yes. motor.Op expects the callback to take two arguments:

``` python
>>> import motor
>>> from bson.objectid import ObjectId
>>> from tornado import gen
>>> @gen.engine
... def get():
...     print (yield motor.Op(func))
... 
>>> def func(callback):
...     callback(ObjectId())
... 
>>> get()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/emptysquare/.virtualenvs/pymongo/lib/python2.7/site-packages/tornado/gen.py", line 120, in wrapper
    runner.run()
  File "/Users/emptysquare/.virtualenvs/pymongo/lib/python2.7/site-packages/tornado/gen.py", line 343, in run
    yielded = self.gen.throw(*exc_info)
  File "<stdin>", line 3, in get
  File "/Users/emptysquare/.virtualenvs/pymongo/lib/python2.7/site-packages/tornado/gen.py", line 335, in run
    next = self.yield_point.get_result()
  File "motor/__init__.py", line 1756, in get_result
    (result, error), _ = super(Op, self).get_result()
TypeError: 'ObjectId' object is not iterable
>>> 
>>> def func(callback):
...     callback(ObjectId(), None)
... 
>>> get()
50c53fd492345017d427e40a
```

The first definition of `func` passes one argument to the callback, so `func` can't be passed to `motor.Op`. The second definition of `func` passes two arguments to the callback, so it **can** be passed to `motor.Op`.

Any function passed to `motor.Op` should take a `callback` argument and pass two arguments to `callback`: a result and an error.
